export default {
  locale: 'en',
  messages: {
    siteTitle: 'MERN Starter Blog',
    addPost: 'Add Post',
    switchLanguage: 'Switch Language',
    twitterMessage: 'We are on Twitter',
    by: 'By',
    registerLink: 'Register',
    registerTitle: 'Register',
    loginLink: 'Login',
    loginTitle: 'Log In',
    logout: 'Logout',
    profileLink: 'Profile',
    profileTitle: ': Change your password',
    username: 'Username',
    password: 'Password',
    routers: 'Routers',
    danger: 'Danger!',
    dashboard: 'Dashboard',
    authority: 'Authority',
    municipality: 'Municipality',
    components: 'Components',
    cameras: 'Cameras',
    cabinets: 'Cabinets',
    firmware: 'Firmware',
    newPassword: 'New password',
    deletePost: 'Delete Post',
    manufacturer: 'Manufacturer',
    createNewPost: 'Create new post',
    createNewRouter: 'New router',
    authorName: 'Author\'s Name',
    pwmData: 'PWM Data',
    postTitle: 'Post Title',
    postContent: 'Post Content',
    model: 'Model',
    submit: 'Submit',
    services: 'Services',
    syslog: 'Syslog',
    tablet: 'Tablet',
    workstation: 'Workstation',
    server: 'Server',
    battery: 'Battery',
    ups: 'Ups',
    VRS: 'VRS',
    'VRS-EVO': 'VRS-EVO',
    AGUIA: 'AGUIA',
    'pwm data': 'PWM Data',
    'ddns monitor': 'DDNS Monitor',
    'mppt data': 'MPPT Data',
    'clear sky': 'Clear sky',
    'few clouds': 'Few clouds',
    'scattered clouds': 'Scattered clouds',
    'broken clouds': 'Broken clouds',
    'shower rain': 'Shower rain',
    'light rain': 'Light rain',
    'moderate rain': 'Moderate rain',
    'overcast clouds': 'Overcast clouds',
    'heavy intensity rain': 'Heavy intensity rain',
    rain: 'Rain',
    thunderstorm: 'Thunderstorm',
    theSearchFor: 'the search for',
    didNotProduceResults: 'did not produce results',
    snow: 'Snow',
    mist: 'Mist',
    dust: 'Dust',
    fog: 'Fog',
    'thunderstorm with heavy rain': 'Thunderstorm with heavy rain',
    'thunderstorm with rain': 'Thunderstorm with rain',
    products: 'Products',
    sim: 'SIM',
    ioLogik: 'ioLogik',
    nas: 'NAS',
    aguia: 'AGUIA',
    vrs: 'VRS',
    vrsEvo: 'VRS-EVO',
    accessPoint: 'Access Point',
    error: 'Error:',
    comment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	}`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
    	  =0 {does not have <i style='font-style: italic'>any</i> comments}
    	  =1 {has <i style='font-style: italic'>#</i> comment}
    	  other {has <i style='font-style: italic'>#</i> comments}
    	}`,
    nestedDateComment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	} as of {date}`,
    activityTrackerUpdated: 'User {username} changed this activity tracker.',
    notificationActivityTrackerUpdated: 'Activity tracker {activityTrackerId} has been updated',
    notificationActivityTrackerCreated: 'Activity tracker {activityTrackerId} was created',
    notificationLicenceActivationRequest: 'Request activation licence for device: {cameraSn}',
    notificationLicenceActivationResponse: 'Confirm activation licence for device: {cameraSn}',
    notificationActivityTrackerNonCompliance: 'Non compliance on activity tracker {activityTrackerId}',
    notificationActivityTrackerNonComplianceSolved: 'Non compliance solved on activity tracker {activityTrackerId}',
    department: 'Department',
  },
};
