export default {
  id: 'Id',
  attachment: 'allegato',
  attachments: 'allegati',
  download: 'Download',
  registerTitle: 'Registrati',
  features: 'Funzioni',
  profile: 'Profilo',
  loginTitle: 'Accedi',
  deactivate: 'Disattiva',
  addNew: 'Inserisci',
  address: 'Indirizzo',
  contacts: 'Contatti',
  datacenter: 'Datacenter',
  vatNumber: 'Partita I.V.A.',
  fiscalCode: 'Cod. fiscale',
  role: 'Ruolo',
  city: 'Località',
  zipCode: 'C.A.P.',
  add: 'Aggiungi',
  deviceInfo: 'Informazioni dispositivo',
  hitCounter: 'Contatore eventi',
  unshare: 'Rimuovi condivisione',
  event: 'Evento',
  title: 'Titolo',
  save: 'Salva',
  timetable: 'Scadenziario',
  owner: 'Proprietario',
  copy: 'Copia',
  duration: 'Durata',
  analyze: 'Analizza',
  description: 'Descrizione',
  maintenenceReference: 'Rif. manutenzione',
  subjectCode: 'Cod. soggetto',
  companyCode: 'Cod. azienda',
  location: 'Località',
  locations: 'Siti',
  map: 'Mappa',
  export: 'Esporta',
  complete: 'Completa',
  nothing: 'Nessuno',
  atTheExpiryDate: 'In corrispondenza',
  activityTracker: 'Activity Tracker',
  minutes: 'minuti',
  fiveMinutesInAdvance: '5 minuti prima',
  tenMinutesInAdvance: '10 minuti prima',
  fifteenMinutesInAdvance: '15 minuti prima',
  oneHourBefore: '1 ora prima',
  twoHoursBefore: '2 ora prima',
  oneDAyBefore: '1 giorno prima',
  twoDaysBefore: '2 giorni prima',
  production: 'Produzione',
  sendToCrm: 'Invia a CRM',
  'S&M': 'Installazione e manutenzione',
  nonCompliance: 'Non conformità',
  generateNonCompliance: 'Genera non conformità',
  solveNonCompliance: 'Risolvi non conformità',
  nonComplianceSolved: 'Non conformità risolta',
  nonComplianceNotSolved: 'Non conformità da risolvere',
  sales: 'Commerciale',
  helpdesk: 'Helpdesk',
  reminder: 'Promemoria',
  onSite: 'In loco',
  creationUser: 'Creato da',
  assign: 'Assegna',
  history: 'Cronologia',
  assignedTo: 'Assegnato a',
  notifyTo: 'Notifica a',
  chargedTo: 'In carico a',
  expirationDate: 'Data scadenza',
  link: 'Collegamento',
  totalTime: 'Tot. tempo',
  closed: 'Chiusa',
  createdOn: 'Data creazione',
  priority: 'Priorità',
  createdBy: 'Creato da',
  model: 'Modello',
  models: 'Modelli',
  username: 'Utente',
  surname: 'Cognome',
  dms: 'DMS',
  users: 'Utenti',
  cellular: 'Cellulare',
  userName: 'Nome utente',
  serialNumber: 'Matricola',
  editProfile: 'Modifica profilo',
  geolocation: 'Geolocazione',
  edit: 'Modifica',
  disabled: 'Disabilitato',
  lastBoot: 'Ultimo riavvio',
  moduleNotPresent: 'Modulo non presente',
  local: 'In locale',
  port: 'Porta',
  loadDefault: 'Carica default',
  remote: 'Da remoto',
  dashboard: 'Dashboard',
  services: 'Servizi',
  syslog: 'Syslog',
  new: 'Nuovo',
  weissNotPresent: 'Weiss non presente',
  path: 'Percorso',
  back: 'Torna',
  filters: 'Filtri',
  addFilter: 'Aggiungi filtro',
  'R&D': 'Ricerca e Sviluppo',
  administration: 'Amministrazione',
  supplier: 'Fornitore',
  parameters: 'Parametri',
  newInstallation: 'Nuova installazione',
  ordinaryActivity: 'Attività ordinaria',
  extraordinaryActivity: 'Attività straordinaria',
  malfunction: 'Malfunzionamento',
  newFeature: 'Nuova funzionalità',
  minWidth: 'Larg. Min.',
  maxWidth: 'Larg. Max.',
  minHeight: 'Alt. Min.',
  maxHeight: 'Alt. Max.',
  info: 'Avviso',
  maps: 'Mappa',
  apply: 'Applica',
  cabinet: 'Quadri elettrici',
  sort: 'Ordinamento',
  site: 'Sito',
  sites: 'Siti',
  undo: 'Annulla',
  inCharge: 'In carico',
  country: 'Provincia',
  province: 'Prov.',
  region: 'Regione',
  searchFor: 'Ricerca per dispositivo, ente o sito',
  searchMessage: 'Ricerca messaggio',
  batteryV: 'Batterie V',
  arrayW: 'Pannelli W',
  arrayV: 'Pannelli V',
  loadV: 'Carico V',
  heightAboveTheRoad: 'Altezza (cm)',
  yellowPointDistance: 'Distanza (cm)',
  cameraSetup: 'Setup telecamere',
  heatsinkC: 'Dissipatore C',
  monitoring: 'Monitoraggio',
  publicIp: 'IP pubblico',
  exportMode: 'Modello di esportazione',
  message: 'Messaggio',
  'ddns monitor': 'DDNS monitor',
  'mppt data': 'MPPT data',
  'pwm data': 'PWM data',
  logout: 'Esci',
  siteTitle: 'Velocar Management System',
  systemCode: 'Codice sistema',
  addPost: 'Add Post',
  switchLanguage: 'Cambia lingua',
  by: 'Da',
  routers: 'Routers',
  deletePost: 'Rimuovi Post',
  time: 'Ora',
  delete: 'Elimina',
  cloneRuleAbove: 'Clona regola sopra',
  cloneRuleUnder: 'Clona regola sotto',
  addRuleAbove: 'Aggiungi regola sopra',
  addRuleBelow: 'Aggiungi regola sotto',
  matchConditions: 'Condizioni di match',
  sourceIp: 'IP sorgente',
  sourceWildcard: 'Wildcard sorgente',
  sourcePort: 'Porta sorgente',
  destinationIp: 'IP destinazione',
  destinationWildcard: 'Wildcard destinazione',
  destinationPort: 'Porta destinazione',
  level: 'Livello',
  telephone: 'Telefono',
  createNewPost: 'Crea post',
  createNewRouter: 'Nuovo router',
  authorName: 'Nome autore',
  postTitle: 'Titolo Post',
  danger: 'Attenzione!',
  postContent: 'Contenuto Post',
  uncheckAll: 'Deseleziona tutto',
  sendSms: 'Invia SMS',
  messages: 'Messaggi',
  hwRevision: 'Rev. Hw',
  submit: 'Invia',
  vehicleClass: 'Classe veicolo',
  weight: 'Peso',
  car: 'Autovetture',
  carWithTrailer: 'Autovetture con carrello',
  lorry: 'Autocarro',
  reload: 'Ricarica',
  lorryWithTrailer: 'Autocarro con rimorchio',
  direction: 'Direzione',
  name: 'Nome',
  operatingMode: 'Modalità operativa',
  motorcycle: 'Motocicli',
  aesEncryption: 'Chiave di encryption',
  bus: 'Autobus',
  other: 'Altro',
  ocrFocal: 'Focale OCR',
  ocrFocus: 'Focus OCR',
  ctxFocal: 'Focale CTX',
  ctxFocus: 'Focus CTX',
  licence: 'Licenze',
  opticalSetup: 'Setup ottico',
  speed: 'Speed',
  ticket: 'Ticket',
  red: 'Red',
  freeFlow: 'Free Flow',
  averageSpeed: 'Velocità media',
  ipAddress: 'Indirizzo IP',
  macAddress: 'Indirizzo MAC',
  warning: 'Attenzione',
  authority: 'Ente',
  authorities: 'Enti',
  products: 'Prodotti',
  components: 'Componenti',
  component: 'Componente',
  camera: 'Telecamera',
  dateTime: 'Data e ora',
  user: 'Utente',
  status: 'Stato',
  cameras: 'Telecamere',
  roadSpeedLimit: 'Limite velocità strada',
  vehicleType: 'Class. video',
  vehicleColor: 'Class. colore',
  manufactureLicence: 'Test',
  purchaseDate: 'Data di acquisto',
  disposalDate: 'Data dismissione',
  changeBattery: 'Sostituisci batterie',
  weiss: 'Box Weiss',
  cabinets: 'Quadri elettrici',
  firmware: 'Firmware',
  batteries: 'Batterie',
  order: 'Commessa',
  orders: 'Commesse',
  downloadAppointment: 'Scarica appuntamento',
  revision: 'Revisione',
  speedTuning: 'Taratura di velocità',
  document: 'Documento',
  documents: 'Documenti',
  totalDocuments: 'Totale documenti',
  digitalSignature: 'Firma digitale',
  insertTuning: 'Inserisci taratura',
  insertRevision: 'Inserisci revisione',
  geometry: 'Geometrie',
  height: 'Altezza',
  distance: 'Distanza',
  focusMin: 'Focus min',
  focusMax: 'Focus max',
  insertNewAT: 'Inserisci nuovo Activity Tracker',
  insertDepartmentOfActivity: 'Inserire reparto attività',
  insertTypeOfActivity: 'Inserire tipologia attività',
  insertTitle: 'Inserire titolo',
  insertLink: 'Inserire collegamento',
  insertDescription: 'Inserire descrizione',
  insertAssignedTo: 'Inserire assegnatari',
  at: 'Alle {dateTime}',
  ok: 'Ok',
  on: 'il',
  date: 'Data',
  code: 'Codice',
  doYouWantToSaveYourNewAT: 'Desideri salvare la nuova attività?',
  activityTimeNotSet: 'In fase di chiusura è necessario imputare il tempo dell\'attività svolta',
  close: 'Chiudi',
  enable: 'Attive',
  disable: 'Disattive',
  enabled: 'Abilitato',
  enableNotifications: 'Abilita notifiche per questo AT',
  disableNotifications: 'Disattiva notifiche per questo AT',
  sim: 'Sim',
  activate: 'Attiva',
  send: 'Invia',
  lastUpdate: 'Ultimo aggiornamento',
  lastChange: 'Ultima modifica',
  signal: 'Segnale',
  activityTime: 'Tempo attività',
  operator: 'Operatore',
  cellNumber: 'Numero cell.',
  rate: 'Probabilità',
  filename: 'Nome file',
  upTime: 'Up Time',
  uploadDocument: 'Carica documento',
  attributes: 'Attributi',
  notes: 'Note',
  todo: 'Da fare',
  focal: 'Focale',
  apertrure: 'Diaframma',
  focus: 'Focus',
  gateway: 'Gateway',
  aperture: 'Diaframma',
  iris: 'Iris level',
  takeCharge: 'Prendi in carico',
  shutter: 'Shutter max',
  gain: 'Gain max',
  done: 'Fatto',
  high: 'Alta',
  type: 'Tipo',
  dimension: 'Dimensioni',
  middle: 'Media',
  medium: 'Media',
  low: 'Bassa',
  ioLogik: 'ioLogik',
  nas: 'Nas',
  accessPoint: 'Access Point',
  tablet: 'Tablet',
  workstation: 'Workstation',
  people: 'Persone',
  server: 'Server',
  battery: 'Batterie',
  clean: 'Pulisci',
  ups: 'Ups',
  VRS: 'VRS',
  show: 'Mostra',
  hide: 'Nascondi',
  day: 'Giorno',
  today: 'Oggi',
  yesterday: 'Ieri',
  thisWeek: 'Questa settimana',
  lastWeek: 'Ultima settimana',
  thisMonth: 'Questo mese',
  lastMonth: 'Lo scorso mese',
  batteryVoltage: 'Voltaggio batterie',
  targetVoltage: 'Voltaggio target',
  chargeCurrent: 'Corrente di carica',
  chargeState: 'Stato di carica',
  outputPower: 'Potenza in uscita',
  ampHours: 'Ampere ora',
  kilowattHours: 'Kilowatt ora',
  heatSink: 'Dissipatore',
  temperatures: 'Temperature',
  dailyValues: 'Valori giornalieri',
  array: 'Pannelli',
  readData: 'Lettura dati',
  arrayVoltage: 'Voltaggio pannelli',
  arrayCurrent: 'Corrente pannelli',
  notifications: 'Notifiche',
  ampereHours: 'Ampere ora',
  commentedOn: 'Data commento',
  batteryTemperature: 'Temperatura batteria',
  markAllAsRead: 'Segna tutte come lette',
  resettableCounters: 'Contatori giornalieri',
  sweepVmp: 'Voltaggio max pannelli',
  sweepVoc: 'Voltaggio max circuito',
  sweepPMax: 'Potenza max uscita',
  showDetail: 'Vedi dettaglio',
  goToList: 'Vai a elenco',
  share: 'Condividi',
  shareWith: 'Condividi con',
  shareWithRead: 'Condividi in lettura',
  shareWithWrite: 'Condividi in scrittura',
  shareR: 'Condivisa (R)',
  shareW: 'Condivisa (RW)',
  read: 'Letta',
  notRead: 'Non letta',
  toRead: 'Da leggere',
  'VRS-EVO': 'VRS-EVO',
  AGUIA: 'AGUIA',
  error: 'Errore:',
  'clear sky': 'Soleggiato',
  'few clouds': 'Poco nuvoloso',
  'scattered clouds': 'Nuvoloso',
  'broken clouds': 'Cielo coperto',
  'shower rain': 'Pioggia intensa',
  'light rain': 'Pioggia leggera',
  'moderate rain': 'Pioggia moderata',
  'overcast clouds': 'Cielo coperto',
  'heavy intensity rain': 'Pioggia forte',
  rain: 'Pioggia',
  thunderstorm: 'Temporale',
  snow: 'Neve',
  mist: 'Nebbia',
  dust: 'Foschia',
  fog: 'Nebbia',
  'thunderstorm with heavy rain': 'Temporale forte',
  'thunderstorm with rain': 'Temporale forte',
  theSearchFor: 'la ricerca di',
  twitterMessage: 'Messaggio tweet',
  didNotProduceResults: 'non ha prodotto risultati',
  comment: 'Commento',
  change: 'Modifica',
  start: 'Inizio',
  end: 'Fine',
  HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
      =0 {does not have <i style='font-style: italic'>any</i> comments}
      =1 {has <i style='font-style: italic'>#</i> comment}
      other {has <i style='font-style: italic'>#</i> comments}
    }`,
  nestedDateComment: `user {name} {value, plural,
      =0 {does not have any comments}
      =1 {has # comment}
      other {has # comments}
    } as of {date}`,
  activityTrackerUpdated: 'L\'utente {username} ha modificato questo activity tracker.',
  notificationActivityTrackerUpdated: 'L\'activity tracker {activityTrackerId} è stato aggiornato',
  notificationActivityTrackerCreated: 'L\'activity tracker {activityTrackerId} è stato creato',
  notificationLicenceActivationRequest: 'Richiesta attivazione licenza per dispositivo sn: {cameraSn}',
  notificationLicenceActivationResponse: 'Conferma attivazione licenza per dispositivo sn: {cameraSn}',
  notificationActivityTrackerNonCompliance: 'Non conformità sull\'activity tracker {activityTrackerId}',
  notificationActivityTrackerNonComplianceSolved: 'Non conformità risolta sull\'activity tracker {activityTrackerId}',
  department: 'Reparto',
  producedCameras: 'Prodotte',
  scrappedCameras: 'Rottamate',
  departing: 'Allontanamento',
  approaching: 'Avvicinamento',
  both: 'Entrambi',
  installedCameras: 'Installate',
  installedPoolCameras: 'Parco installate',
  activatedCameras: 'Con licenza attiva',
  configuredCameras: 'Configurate',
  coveredByOrderCameras: 'Coperte da commessa',
  totalOrders: 'Totale commesse',
  VEOrderType: 'Vendita',
  NOOrderType: 'Noleggio',
  MAOrderType: 'Manutenzione',
  INOrderType: 'Solo intervento',
  SEROrderType: 'Service & Trade',
  totalRouters: 'Totale router',
  activeRouters: 'Router attivi',
  inactiveRouters: 'Router non attivi',
  averageLinkUpPercentageRouters: '% Link Up',
  averageUpTimePercentageRouters: '% Up Time',
  totalServers: 'Totale server',
  availableServers: 'Server raggiungibili',
  notAvailableServers: 'Server non raggiungibili',
  router: 'router',
  totalAT: 'Totale activity tracker',
  todoAT: 'Da fare',
  inChargeAT: 'Presi in carico',
  doneAT: 'Fatti',
  closedAT: 'Chiusi',
  solvedNC: 'Non conformità risolte',
  notSolvedNC: 'Non conformità da risolvere',
  internalNC: 'Interna',
  customerNC: 'Cliente',
  resellerNC: 'Rivenditore',
  lowAT: 'AT priorità bassa',
  mediumAT: 'AT priorità media',
  highAT: 'AT priorità alta',
  salesAT: 'Commerciale',
  helpdeskAT: 'Helpdesk',
  'S&MAT': 'Installazione e manutenzione',
  'R&DAT': 'Ricerca e sviluppo',
  productionAT: 'Produzione',
  administrationAT: 'Amministrazione',
  supplierAT: 'Fornitore',
  newInstallationAT: 'Nuova installazione',
  ordinaryActivityAT: 'Attività ordinaria',
  extraordinaryActivityAT: 'Attività straordinaria',
  malfunctionAT: 'Malfunzionamento',
  newFeatureAT: 'Nuova funzionalità',
  installedModels: 'Modelli installati',
  month: 'Mese',
  year: 'Anno',
  cabinetDoorOpen: 'Quadro elettrico aperto',
  cabinetDoorClosed: 'Quadro elettrico chiuso',
  releOn: 'Relè ON',
  releOff: 'Relè OFF',
  scrap: 'Rottama',
  origin: 'Origine',
  internal: 'Interna',
  customer: 'Cliente',
  reseller: 'Rivenditore',
  CERT_CONT_PER: 'Certificato di controllo periodico',
  CHK_APP_VSP: 'Configurazione apparato in VSP',
  CHK_FINE_INST: 'CheckList fine installazione sito',
  CHK_REMOTE: 'CheckList verifiche remote sito',
  CONF: 'Dichiarazione di corrispondenza al prototipo',
  CORR_INST: 'Certificato di corretta installazione',
  IMG_SITO: 'Immagini sito',
  MOD_COL: 'Modulo di collaudo',
  RAP_CP: 'Revisione',
  VERB_ATT: 'Verbale attivazione impianto',
  SIT: 'Taratura periodica',
  SIT_INIZIALE: 'Taratura iniziale',
  TRAIN_CLI: 'Formazione cliente',
  VERBALE: 'Verbale fine installazione sito',
  prefectoralDecree: 'Decreto prefettizio',
  trafficLight: 'Semaforo',
  ztl: 'ZTL',
  custom: 'Personalizzato',
  group: 'Gruppo',
  action: 'Azione',
  protocol: 'Protocollo',
  source: 'Sorgente',
  destination: 'Destinazione',
  number: 'Numero',
  provider: 'Operatore',
  fixed: 'Fissa',
  portable: 'Portatile',
  triggerOpto: 'Trigger optoisolato',
  dayNightly: 'Giorno (ore notturne)',
  dayOfWeek: 'Giorno della settimana',
  dayOfWeekNightly: 'Giorno della settimana (ore notturne)',
  selectPosition: 'Seleziona posizione',
  hour: 'Ora',
  week: 'Settimana',
  settings: 'Impostazioni',
  forms: 'Moduli',
  negotiation: 'Trattativa',
  negotiations: 'Trattative',
  offers: 'Offerte',
  jobCards: 'Schede commessa',
  inspections: 'Sopralluoghi',
  newNegotiation: 'Nuova trattativa',
  contact: 'Contatto',
  success: 'Probabilità di successo',
  email: 'E-mail',
  subject: 'Oggetto',
  insert: 'Inserisci',
  totalAmount: 'Totale',
  totalOffer: 'Tot. offerta',
  totalNegotiations: 'Tot. trattative',
  totalNegotiation: 'Tot. trattativa',
  sale: 'Vendita',
  rent: 'Noleggio',
  items: 'Articoli',
  yes: 'Sì',
  no: 'No',
  isGreaterThan: 'è maggiore di',
  isLessThan: 'è minore di',
  isEqual: 'è uguale a',
  isNotEqual: 'è diverso da',
  isBetween: 'è tra i valori',
  contains: 'contiene',
  doesNotContain: 'non contiene',
  startWith: 'inizia con',
  endsWith: 'finisce con',
  opened: 'Aperta',
  suspended: 'Sospesa',
  negativelyClosed: 'Chiusa negativamente',
  successfullyClosed: 'Chiusa positivamente',
};
