apiVersion: v1
kind: Service
metadata:
  name: vms-crm
  namespace: vms
  labels:
    app.kubernetes.io/name: vms-crm
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: vms-crm
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31102
      protocol: TCP
      name: vms-crm
